/*
  THE ASK BAR'S GROUNDING AND ITS CHAT LEADS, 2026-09-24.

  Grounding: the object reference in Code.js is generated from a real org by
  scripts/object_reference.py. These tests do not re-check Salesforce; they check
  that the reference is present, reaches both providers' prompt, and that the
  lines for objects a visitor names are repeated beside the question - the part
  that turned "ProductItem has no SerialNumber field" into "Yes" on the live page.

  Leads: a visitor who types an email becomes one Web-to-Lead post to the SFDC24
  dev org, from the server, without leaving the page. Once per conversation, off
  with CHAT_LEADS=off, and before the spend gates so a capped chat still captures.
*/
'use strict';

const assert = require('node:assert/strict');
const test = require('node:test');
const vm = require('node:vm');
const { gasRead } = require('./gas_source.cjs');

const CODE = gasRead('governor-page-api', 'Code');

function load(props = {}, { status = 200 } = {}) {
  const posts = [];
  const cache = new Map();
  const store = Object.assign({}, props);
  const ctx = {
    console,
    PropertiesService: { getScriptProperties: () => ({
      getProperty: k => (k in store ? store[k] : null),
      setProperty: (k, v) => { store[k] = String(v); },
      getProperties: () => Object.assign({}, store),
      deleteProperty: k => { delete store[k]; },
    }) },
    CacheService: { getScriptCache: () => ({
      get: k => (cache.has(k) ? cache.get(k) : null), put: (k, v) => cache.set(k, String(v)),
      remove: k => cache.delete(k),
    }) },
    LockService: { getScriptLock: () => ({ waitLock() {}, releaseLock() {} }) },
    UrlFetchApp: { fetch: (url, opts) => {
      posts.push({ url, opts });
      const code = typeof status === 'function' ? status(posts.length) : status;
      if (code === 'throw') throw new Error('socket hang up');
      return { getResponseCode: () => code };
    } },
    ContentService: {}, HtmlService: {}, SpreadsheetApp: {}, Session: {},
    Utilities: { formatDate: (d) => d.toISOString().slice(0, 10).replace(/-/g, '') },
  };
  vm.createContext(ctx);
  vm.runInContext(CODE, ctx);
  ctx.logVisitor_ = () => {};
  return { ctx, posts, store, cache };
}

test('the reference is generated, non-empty, and names the objects it covers', () => {
  const { ctx } = load();
  assert.match(CODE, /generated by scripts\/object_reference\.py/);
  assert.ok(ctx.OBJECT_REFERENCE_.length > 5000, 'reference was emptied');
  assert.ok(ctx.OBJECT_REFERENCE_OBJECTS_.includes('ProductItem'));
  for (const name of ctx.OBJECT_REFERENCE_OBJECTS_) {
    assert.match(ctx.OBJECT_REFERENCE_, new RegExp('(^|\\n)' + name + ': '), name);
  }
});

test('both providers get the reference and the grounding rule', () => {
  const { ctx } = load();
  for (const who of ['claude', 'codex']) {
    const prompt = ctx.SYSTEM_PROMPT_(who);
    assert.ok(prompt.includes(ctx.OBJECT_REFERENCE_), who);
    assert.match(prompt, /OBJECT AND FIELD FACTS COME ONLY FROM THE OBJECT REFERENCE/);
    assert.match(prompt, /The reference overrides what you remember/);
  }
});

test('the rule is placed before the call-first bullets, not after them', () => {
  // Finding 6a: a precondition placed after an instruction in capitals lost.
  const { ctx } = load();
  const prompt = ctx.SYSTEM_PROMPT_('claude');
  assert.ok(prompt.indexOf('OBJECT AND FIELD FACTS') < prompt.indexOf('NAME THE CALL FIRST'));
});

test('objects the visitor names are repeated beside the question', () => {
  const { ctx } = load();
  assert.equal(ctx.focusReference_('hello there'), '');
  const f = ctx.focusReference_('Can I store a serial number on a product item?');
  assert.match(f, /^ProductItem: /);
  assert.equal(ctx.focusReference_('ProductItems and product items').split('\n').length, 1);
  ctx.FOCUS_REFERENCE_ = f;
  assert.match(ctx.SYSTEM_PROMPT_('claude'), /OBJECTS NAMED IN THIS CONVERSATION[\s\S]*ProductItem: /);
  ctx.FOCUS_REFERENCE_ = '';
  assert.doesNotMatch(ctx.SYSTEM_PROMPT_('claude'), /OBJECTS NAMED IN THIS CONVERSATION/);
});

test('the focus set is computed from the conversation before the provider call', () => {
  const body = CODE.slice(CODE.indexOf('function receptionWithIdentity_'));
  const focus = body.indexOf('FOCUS_REFERENCE_ = focusReference_(');
  assert.ok(focus > 0 && focus < body.indexOf('.go()'));
});

test('no email, no lead', () => {
  const { ctx, posts } = load();
  assert.equal(ctx.captureChatLead_('ca_x', 'how do I export all records?', [], ctx.PropertiesService.getScriptProperties()), false);
  assert.equal(posts.length, 0);
});

test('an email becomes one Web-to-Lead post to the SFDC24 dev org', () => {
  const { ctx, posts } = load();
  const props = ctx.PropertiesService.getScriptProperties();
  const history = [{ role: 'user', text: "Hi, I'm Jane Doe, we need Flow help" },
                   { role: 'assistant', text: 'Happy to help.' }];
  assert.equal(ctx.captureChatLead_('ca_1', 'reach me at jane@acme.io', history, props), true);
  assert.equal(posts.length, 1);
  const { url, opts } = posts[0];
  assert.match(url, /^https:\/\/webto\.salesforce\.com\/servlet\/servlet\.WebToLead/);
  assert.equal(opts.payload.oid, '00Dbm00000wK2ibEAC');
  assert.equal(opts.payload.lead_source, 'sfdc24.com');
  assert.equal(opts.payload.email, 'jane@acme.io');
  assert.equal(opts.payload.first_name, 'Jane');
  assert.equal(opts.payload.last_name, 'Doe');
  assert.equal(opts.payload.company, 'acme.io');
  assert.match(opts.payload.description, /Visitor: Hi, I'm Jane Doe[\s\S]*Visitor: reach me at jane@acme\.io/);
});

test('one lead per conversation, and a new conversation gets its own', () => {
  const { ctx, posts } = load();
  const props = ctx.PropertiesService.getScriptProperties();
  ctx.captureChatLead_('ca_1', 'a@b.co', [], props);
  ctx.captureChatLead_('ca_1', 'again a@b.co', [], props);
  assert.equal(posts.length, 1);
  ctx.captureChatLead_('ca_2', 'c@d.co', [], props);
  assert.equal(posts.length, 2);
});

test('a free-mail domain is not recorded as the company, and a missing name falls back', () => {
  const { ctx } = load();
  const f = ctx.chatLeadFields_('sam.k@gmail.com', []);
  assert.equal(f.company, '[not provided]');
  assert.equal(f.last_name, 'sam.k');
  assert.equal(f.first_name, '');
});

test('CHAT_LEADS=off stops capture', () => {
  const { ctx, posts } = load({ CHAT_LEADS: 'off' });
  assert.equal(ctx.captureChatLead_('ca_1', 'x@y.co', [], ctx.PropertiesService.getScriptProperties()), false);
  assert.equal(posts.length, 0);
});

test('capture runs before the spend gates, so a capped chat still records the lead', () => {
  const body = CODE.slice(CODE.indexOf('function receptionWithIdentity_'));
  const capture = body.indexOf('captureChatLead_(sid');
  assert.ok(capture > 0);
  assert.ok(capture < body.indexOf("=== 'off'"), 'capture after the CHAT_ENABLED switch');
  assert.ok(capture < body.indexOf('reserveChatBudget_('), 'capture after the budget gate');
});

// Codex review of PR 195, P1: conversations are free to mint, so a per-
// conversation guard alone let 150 synthetic identities make 150 Lead posts.
test('150 fresh conversations cannot make more Leads than the daily cap', () => {
  const { ctx, posts } = load();
  const props = ctx.PropertiesService.getScriptProperties();
  for (let i = 0; i < 150; i += 1) ctx.captureChatLead_('ca_' + i, 'x' + i + '@y.co', [], props);
  assert.equal(posts.length, 25);
});

test('the daily cap is a Script Property', () => {
  const { ctx, posts } = load({ CHAT_LEADS_DAILY_CAP: '3' });
  const props = ctx.PropertiesService.getScriptProperties();
  for (let i = 0; i < 10; i += 1) ctx.captureChatLead_('ca_' + i, 'x' + i + '@y.co', [], props);
  assert.equal(posts.length, 3);
});

// P3 and the re-review's P2: a refused post may retry, but an UNKNOWN outcome
// (5xx, or a lost response) is never retried - the Lead may already exist.
test('a 4xx is released so the next email retries; a sent one is not resent', () => {
  const { ctx, posts } = load({}, { status: (n) => (n === 1 ? 400 : 200) });
  const props = ctx.PropertiesService.getScriptProperties();
  assert.equal(ctx.captureChatLead_('ca_1', 'a@b.co', [], props), false);
  assert.equal(ctx.captureChatLead_('ca_1', 'a@b.co', [], props), true);
  assert.equal(ctx.captureChatLead_('ca_1', 'a@b.co', [], props), false);
  assert.equal(posts.length, 2);
});

test('an unknown outcome is never retried automatically', () => {
  for (const status of [503, 'throw']) {
    const { ctx, posts } = load({}, { status });
    const props = ctx.PropertiesService.getScriptProperties();
    assert.equal(ctx.captureChatLead_('ca_1', 'a@b.co', [], props), false);
    assert.equal(ctx.captureChatLead_('ca_1', 'a@b.co', [], props), false);
    assert.equal(posts.length, 1, String(status));
  }
});

test('once per conversation survives losing the cache - the record is durable', () => {
  const { ctx, posts } = load();
  const props = ctx.PropertiesService.getScriptProperties();
  ctx.captureChatLead_('ca_1', 'a@b.co', [], props);
  ctx.CacheService = { getScriptCache: () => ({ get: () => null, put() {}, remove() {} }) };
  ctx.captureChatLead_('ca_1', 'a@b.co', [], props);
  assert.equal(posts.length, 1);
});

// Second re-review of PR 195: a conversation token lives 14 days, and v57-v60
// left their own counters and receipts behind.
const dayKey = (daysAgo) => 'LEAD_DAY_' + new Date(Date.now() - daysAgo * 86400000)
  .toISOString().slice(0, 10).replace(/-/g, '');

test('a conversation that returns ten days later does not send a second lead', () => {
  const { ctx, posts } = load({ [dayKey(10)]: JSON.stringify({ n: 1, keys: { ca_1: 'sent' } }) });
  assert.equal(ctx.captureChatLead_('ca_1', 'a@b.co', [], ctx.PropertiesService.getScriptProperties()), false);
  assert.equal(posts.length, 0);
});

test('an unknown outcome from days ago is still never retried', () => {
  const { ctx, posts } = load({ [dayKey(6)]: JSON.stringify({ n: 1, keys: { ca_1: 'unknown' } }) });
  ctx.captureChatLead_('ca_1', 'a@b.co', [], ctx.PropertiesService.getScriptProperties());
  assert.equal(posts.length, 0);
});

test('records older than the token window are deleted, so storage stays bounded', () => {
  const { ctx, store } = load({ [dayKey(20)]: JSON.stringify({ n: 3, keys: { old: 'sent' } }) });
  ctx.captureChatLead_('ca_9', 'z@y.co', [], ctx.PropertiesService.getScriptProperties());
  assert.equal(dayKey(20) in store, false);
});

test('the v57-v60 counter and cache receipt carry forward', () => {
  const today = dayKey(0).slice('LEAD_DAY_'.length);
  const capped = load({ ['LEAD_COUNT_' + today]: '25' });
  assert.equal(capped.ctx.captureChatLead_('ca_1', 'a@b.co', [], capped.ctx.PropertiesService.getScriptProperties()), false);
  assert.equal(capped.posts.length, 0, 'the old counter still counts against today');
  const receipt = load();
  receipt.cache.set('lead_ca_2', 'sent');
  assert.equal(receipt.ctx.captureChatLead_('ca_2', 'a@b.co', [], receipt.ctx.PropertiesService.getScriptProperties()), false);
  assert.equal(receipt.posts.length, 0, 'the old cache receipt still counts as sent');
});

// Third re-review of PR 195 (P2): the old cache receipt expires in 6 hours, the
// token lives 14 days. A hit must become durable before the cache forgets it.
test('an old cache receipt survives its own expiry: hit, cache expires, same token, no second lead', () => {
  for (const legacy of ['sent', 'pending']) {
    const { ctx, posts, cache, store } = load();
    const props = ctx.PropertiesService.getScriptProperties();
    cache.set('lead_ca_3', legacy);
    assert.equal(ctx.captureChatLead_('ca_3', 'a@b.co', [], props), false);
    cache.clear();                                            // 6h5m later
    assert.equal(ctx.captureChatLead_('ca_3', 'a@b.co', [], props), false, legacy);
    assert.equal(posts.length, 0, legacy + ': the same conversation never posts again');
    const day = JSON.parse(store[dayKey(0)]);
    assert.equal(day.keys.ca_3, legacy === 'sent' ? 'sent' : 'unknown');
    assert.equal(day.n, 0, 'promoting a receipt takes no reservation');
  }
});

// P2: the reference omits system and audit fields on purpose, so the prompt
// must not call its list complete for those.
test('the grounding rule never lets an omitted system field read as absent', () => {
  const { ctx } = load();
  const prompt = ctx.SYSTEM_PROMPT_('claude');
  assert.match(prompt, /OwnerId/);
  assert.match(prompt, /never deny one/i);
  assert.doesNotMatch(prompt, /its list of standard fields is complete/);
  // Re-review P2: one org's configuration is not Salesforce's defaults, and an
  // unlisted field is unknown, not absent.
  assert.doesNotMatch(prompt, /delivered/);
  assert.doesNotMatch(prompt, /is not a standard field/);
  assert.match(prompt, /cannot confirm it from here - never that it does not exist/);
});

// 2026-09-24: first-tier admin tasks. Live answers missed Data Loader on
// "extract all records", invented "150 million records per object", and led
// with an older route on email import.
test('both providers get the first-tier admin reference and the numbers rule', () => {
  const { ctx } = load();
  for (const who of ['claude', 'codex']) {
    const prompt = ctx.SYSTEM_PROMPT_(who);
    assert.match(prompt, /ADMIN TASK REFERENCE/, who);
    assert.match(prompt, /Salesforce Files[\s\S]*Upload Files/, who);
    assert.match(prompt, /exactly one profile[\s\S]*permission sets/, who);
    assert.match(prompt, /permission set groups, which are assigned to the user directly[^"]*never added to a profile/, who);
    assert.match(prompt, /Data Export service[\s\S]*Data Loader's Export[\s\S]*Export All/, who);
    assert.match(prompt, /Outlook integration[\s\S]*Gmail integration[\s\S]*Einstein Activity Capture[\s\S]*Email to Salesforce/, who);
    assert.match(prompt, /record-triggered Flow[^"]*only when a record is updated to meet the condition requirements[^"]*sends again/, who);
    assert.match(prompt, /Login IP Ranges: set on the profile only; a permission set cannot carry IP ranges/, who);
    assert.match(prompt, /AND\(NOT\(ISNEW\(\)\), ISPICKVAL\(PRIORVALUE\(StageName\), "Closed Won"\)\)/, who);
    assert.match(prompt, /NUMBERS ARE FACTS TOO/, who);
    assert.ok(prompt.indexOf('ADMIN TASK REFERENCE') < prompt.indexOf('OBJECT REFERENCE -'),
      'the task reference comes before the long object reference');
    assert.doesNotMatch(prompt, /150 million/, who);
  }
});

// Codex review of #215 (P2): Einstein Activity Capture's storage depends on
// configuration. With "Sync Email as Salesforce Activity" matched email is
// stored as EmailMessage + Task (current Salesforce help); only setups without
// it keep email outside standard activities. Never assert one mode as the rule.
test('Einstein Activity Capture is described by configuration, never as one fixed limitation', () => {
  const { ctx } = load();
  for (const who of ['claude', 'codex']) {
    const prompt = ctx.SYSTEM_PROMPT_(who);
    assert.match(prompt, /Sync Email as Salesforce Activity turned on, matched emails are stored as standard email and task records/, who);
    assert.match(prompt, /setups without that setting keep captured email outside the standard activity records/, who);
    assert.match(prompt, /Never assume which one a visitor has/, who);
    assert.doesNotMatch(prompt, /what it captures is not stored as standard activity records/, who);
  }
});

