/*
  THE ASK BAR'S GROUNDING AND ITS CHAT LEADS, 2026-09-24.

  Grounding: the object reference in Code.js is generated from a real org by
  scripts/object_reference.py. These tests do not re-check Salesforce; they check
  that the reference is present, reaches both providers' prompt, and that the
  lines for objects a visitor names are repeated beside the question - the part
  that turned "ProductItem has no SerialNumber field" into "Yes" on the live page.

  Leads: a visitor who types an email becomes one Web-to-Lead post to the SFDC24
  dev org, from the server, without leaving the page. Once per conversation, off
  with CHAT_LEADS=off, and before the spend gates so a capped chat still captures.
*/
'use strict';

const assert = require('node:assert/strict');
const test = require('node:test');
const vm = require('node:vm');
const { gasRead } = require('./gas_source.cjs');

const CODE = gasRead('governor-page-api', 'Code');

function load(props = {}) {
  const posts = [];
  const cache = new Map();
  const ctx = {
    console,
    PropertiesService: { getScriptProperties: () => ({ getProperty: k => (k in props ? props[k] : null) }) },
    CacheService: { getScriptCache: () => ({
      get: k => (cache.has(k) ? cache.get(k) : null), put: (k, v) => cache.set(k, String(v)),
    }) },
    LockService: { getScriptLock: () => ({ waitLock() {}, releaseLock() {} }) },
    UrlFetchApp: { fetch: (url, opts) => { posts.push({ url, opts }); return { getResponseCode: () => 200 }; } },
    ContentService: {}, HtmlService: {}, Utilities: {}, SpreadsheetApp: {}, Session: {},
  };
  vm.createContext(ctx);
  vm.runInContext(CODE, ctx);
  ctx.logVisitor_ = () => {};
  return { ctx, posts };
}

test('the reference is generated, non-empty, and names the objects it covers', () => {
  const { ctx } = load();
  assert.match(CODE, /generated by scripts\/object_reference\.py/);
  assert.ok(ctx.OBJECT_REFERENCE_.length > 5000, 'reference was emptied');
  assert.ok(ctx.OBJECT_REFERENCE_OBJECTS_.includes('ProductItem'));
  for (const name of ctx.OBJECT_REFERENCE_OBJECTS_) {
    assert.match(ctx.OBJECT_REFERENCE_, new RegExp('(^|\\n)' + name + ': '), name);
  }
});

test('both providers get the reference and the grounding rule', () => {
  const { ctx } = load();
  for (const who of ['claude', 'codex']) {
    const prompt = ctx.SYSTEM_PROMPT_(who);
    assert.ok(prompt.includes(ctx.OBJECT_REFERENCE_), who);
    assert.match(prompt, /OBJECT AND FIELD FACTS COME ONLY FROM THE OBJECT REFERENCE/);
    assert.match(prompt, /The reference overrides what you remember/);
  }
});

test('the rule is placed before the call-first bullets, not after them', () => {
  // Finding 6a: a precondition placed after an instruction in capitals lost.
  const { ctx } = load();
  const prompt = ctx.SYSTEM_PROMPT_('claude');
  assert.ok(prompt.indexOf('OBJECT AND FIELD FACTS') < prompt.indexOf('NAME THE CALL FIRST'));
});

test('objects the visitor names are repeated beside the question', () => {
  const { ctx } = load();
  assert.equal(ctx.focusReference_('hello there'), '');
  const f = ctx.focusReference_('Can I store a serial number on a product item?');
  assert.match(f, /^ProductItem: /);
  assert.equal(ctx.focusReference_('ProductItems and product items').split('\n').length, 1);
  ctx.FOCUS_REFERENCE_ = f;
  assert.match(ctx.SYSTEM_PROMPT_('claude'), /OBJECTS NAMED IN THIS CONVERSATION[\s\S]*ProductItem: /);
  ctx.FOCUS_REFERENCE_ = '';
  assert.doesNotMatch(ctx.SYSTEM_PROMPT_('claude'), /OBJECTS NAMED IN THIS CONVERSATION/);
});

test('the focus set is computed from the conversation before the provider call', () => {
  const body = CODE.slice(CODE.indexOf('function receptionWithIdentity_'));
  const focus = body.indexOf('FOCUS_REFERENCE_ = focusReference_(');
  assert.ok(focus > 0 && focus < body.indexOf('.go()'));
});

test('no email, no lead', () => {
  const { ctx, posts } = load();
  assert.equal(ctx.captureChatLead_('ca_x', 'how do I export all records?', [], ctx.PropertiesService.getScriptProperties()), false);
  assert.equal(posts.length, 0);
});

test('an email becomes one Web-to-Lead post to the SFDC24 dev org', () => {
  const { ctx, posts } = load();
  const props = ctx.PropertiesService.getScriptProperties();
  const history = [{ role: 'user', text: "Hi, I'm Jane Doe, we need Flow help" },
                   { role: 'assistant', text: 'Happy to help.' }];
  assert.equal(ctx.captureChatLead_('ca_1', 'reach me at jane@acme.io', history, props), true);
  assert.equal(posts.length, 1);
  const { url, opts } = posts[0];
  assert.match(url, /^https:\/\/webto\.salesforce\.com\/servlet\/servlet\.WebToLead/);
  assert.equal(opts.payload.oid, '00Dbm00000wK2ibEAC');
  assert.equal(opts.payload.lead_source, 'sfdc24.com');
  assert.equal(opts.payload.email, 'jane@acme.io');
  assert.equal(opts.payload.first_name, 'Jane');
  assert.equal(opts.payload.last_name, 'Doe');
  assert.equal(opts.payload.company, 'acme.io');
  assert.match(opts.payload.description, /Visitor: Hi, I'm Jane Doe[\s\S]*Visitor: reach me at jane@acme\.io/);
});

test('one lead per conversation, and a new conversation gets its own', () => {
  const { ctx, posts } = load();
  const props = ctx.PropertiesService.getScriptProperties();
  ctx.captureChatLead_('ca_1', 'a@b.co', [], props);
  ctx.captureChatLead_('ca_1', 'again a@b.co', [], props);
  assert.equal(posts.length, 1);
  ctx.captureChatLead_('ca_2', 'c@d.co', [], props);
  assert.equal(posts.length, 2);
});

test('a free-mail domain is not recorded as the company, and a missing name falls back', () => {
  const { ctx } = load();
  const f = ctx.chatLeadFields_('sam.k@gmail.com', []);
  assert.equal(f.company, '[not provided]');
  assert.equal(f.last_name, 'sam.k');
  assert.equal(f.first_name, '');
});

test('CHAT_LEADS=off stops capture', () => {
  const { ctx, posts } = load({ CHAT_LEADS: 'off' });
  assert.equal(ctx.captureChatLead_('ca_1', 'x@y.co', [], ctx.PropertiesService.getScriptProperties()), false);
  assert.equal(posts.length, 0);
});

test('capture runs before the spend gates, so a capped chat still records the lead', () => {
  const body = CODE.slice(CODE.indexOf('function receptionWithIdentity_'));
  const capture = body.indexOf('captureChatLead_(sid');
  assert.ok(capture > 0);
  assert.ok(capture < body.indexOf("=== 'off'"), 'capture after the CHAT_ENABLED switch');
  assert.ok(capture < body.indexOf('reserveChatBudget_('), 'capture after the budget gate');
});
