"""Build the ask bar's object reference from a real org, never from recall.

WHY THIS EXISTS. On 2026-09-24 seven reworded object-model questions went
through the live ask bar. About one came back right. The model said
SerializedProduct has no Status field (it has one, and Available is a value of
it), that SerializedProduct has no lookup to ProductItem (it has
ProductItemId), and it named a "Product Transfer Line Item" object that does
not exist. The regex table in sfdc24-site grounds only exact phrasings, so any
rewording reached the model with nothing to stand on.

THE RULE THIS FILE ENFORCES. Every fact in the reference comes from
`sf sobject describe` against an org, in this run. Nothing is typed in by hand,
because the last hand-typed fact was the model's own wrong answer promoted to
ground truth (sfdc24-site #129, corrected in #132).

The output replaces the block between the two OBJECT REFERENCE markers in
apps-script/governor-page-api/Code.js. It lives in Code.js rather than its own
file so the suites that load Code.js alone see exactly what production sees.

    python scripts/object_reference.py [--org PlaygroundOrg] [--check]

--check exits 1 if Code.js does not hold what the org describes today.
"""
import argparse
import datetime
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CODE = os.path.join(ROOT, "apps-script", "governor-page-api", "Code.js")
BEGIN = "// ---- OBJECT REFERENCE: generated by scripts/object_reference.py, do not edit ----"
END = "// ---- END OBJECT REFERENCE ----"

# The subject this site is asked about and was measured getting wrong: Field
# Service inventory and the work-order path it hangs off, plus the core CRM
# objects every admin question touches. Bounded on purpose - the prompt carries
# all of it on every call.
OBJECTS = [
    "Product2", "ProductItem", "ProductItemTransaction", "SerializedProduct",
    "SerializedProductTransaction", "ProductTransfer", "ProductTransferState",
    "ProductRequest", "ProductRequestLineItem", "ProductRequired",
    "ProductConsumed", "ReturnOrder", "ReturnOrderLineItem", "Shipment",
    "Location", "Asset", "WorkOrder", "WorkOrderLineItem", "WorkType",
    "ServiceAppointment", "ServiceResource", "ServiceTerritory",
    "Account", "Contact", "Lead", "Opportunity", "OpportunityLineItem", "Case",
]

# Audit and plumbing fields every object carries. They answer no visitor
# question and would double the prompt.
SKIP = {
    "Id", "IsDeleted", "CreatedById", "CreatedDate", "LastModifiedById",
    "LastModifiedDate", "SystemModstamp", "LastViewedDate", "LastReferencedDate",
    "OwnerId", "CurrencyIsoCode", "RecordTypeId", "MasterRecordId",
    "Jigsaw", "JigsawCompanyId", "JigsawContactId", "PhotoUrl", "CleanStatus",
}
MAX_PICKLIST = 15


def describe(obj, org):
    cmd = ["sf", "sobject", "describe", "-s", obj, "-o", org, "--json"]
    out = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8",
                         shell=(os.name == "nt"))
    try:
        return json.loads(out.stdout).get("result")
    except ValueError:
        return None


def field_line(f):
    t = f["type"]
    if t == "reference" and f.get("referenceTo"):
        return "%s -> %s" % (f["name"], "|".join(f["referenceTo"][:4]))
    if t in ("picklist", "multipicklist"):
        vals = [p["value"] for p in f.get("picklistValues", []) if p.get("active")]
        if not vals:
            return "%s picklist" % f["name"]
        if len(vals) > MAX_PICKLIST:
            return "%s picklist (%d values)" % (f["name"], len(vals))
        return "%s picklist [%s]" % (f["name"], ", ".join(vals))
    return "%s %s" % (f["name"], t)


def build(org):
    lines, missing = [], []
    for obj in OBJECTS:
        d = describe(obj, org)
        if not d:
            missing.append(obj)
            continue
        fields = [f for f in d["fields"] if not f["custom"] and f["name"] not in SKIP]
        fields.sort(key=lambda f: f["name"])
        lines.append("%s: %s" % (obj, "; ".join(field_line(f) for f in fields)))
    return lines, missing


def render(lines, missing, org, day):
    text = "\n".join(lines)
    body = [
        BEGIN,
        "// Source: `sf sobject describe` against org alias " + org + " on " + day + ".",
        "// Standard fields only, audit fields omitted. Objects absent from that org: "
        + (", ".join(missing) or "none") + ".",
        "var OBJECT_REFERENCE_ = " + json.dumps(text, ensure_ascii=True) + ";",
        "var OBJECT_REFERENCE_OBJECTS_ = " + json.dumps(
            [l.split(":", 1)[0] for l in lines]) + ";",
        END,
    ]
    return "\n".join(body)


def splice(code, block):
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(code):
        raise SystemExit("markers not found in Code.js")
    return pat.sub(lambda m: block, code, count=1)


def strip_date(s):
    return re.sub(r" on \d{4}-\d{2}-\d{2}\.", " on DATE.", s)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--org", default="PlaygroundOrg")
    ap.add_argument("--code", default=CODE)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    lines, missing = build(a.org)
    if not lines:
        raise SystemExit("describe returned nothing - refusing to write an empty reference")
    day = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    block = render(lines, missing, a.org, day)
    with open(a.code, encoding="utf-8", newline="") as fh:
        code = fh.read()
    new = splice(code, block)
    if a.check:
        same = strip_date(new) == strip_date(code)
        print("reference matches the org" if same else "REFERENCE DRIFT: re-run without --check")
        sys.exit(0 if same else 1)
    with open(a.code, "w", encoding="utf-8", newline="") as fh:
        fh.write(new)
    print("%d objects, %d chars; absent: %s" % (
        len(lines), len("\n".join(lines)), ", ".join(missing) or "none"))


if __name__ == "__main__":
    main()
